import Foundation

enum SMSDiagnosticsTests {
    static func run() throws -> Int {
        var checks = 0
        func expect(_ condition: Bool, _ label: String) throws {
            checks += 1
            guard condition else { throw AppFailure.message("FAIL: \(label)") }
        }
        let receivedAt = ISO8601DateFormatter().date(from: "2026-10-03T06:08:20Z")!
        let body = "尾号XXXX卡10月3日14:08支出(消费财付通-测试商户)34.50元，余额111.11元。【工商银行】"
        var enabled = Snapshot(); enabled.autoRecordSMS = true
        let normal = try SMSInboxPolicy.accept(body: body, sender: "95588", requestID: nil, receivedAt: receivedAt, into: enabled)
        try expect(normal.snapshot.transactions.first?.cents == 3450 && normal.snapshot.smsInbox.first?.status == .recorded, "masked direct-payment shape automatically records the transaction amount")
        try expect(normal.snapshot.transactions.first?.bankBalanceAfterCents == 11111, "masked direct-payment balance remains separate from transaction amount")
        let small = try SMSInboxPolicy.accept(body: body.replacingOccurrences(of: "34.50元", with: "0.01元"), sender: "95588", requestID: nil, receivedAt: receivedAt, into: enabled)
        try expect(small.snapshot.transactions.first?.cents == 1 && small.snapshot.smsInbox.first?.status == .recorded, "one-cent bank SMS is accepted without a ten-yuan threshold")

        try expect(SMSReceptionDiagnostics.inputProblem(body: " \n ", requestID: nil) == .emptyBody, "diagnosis identifies absent shortcut message input")
        try expect(SMSReceptionDiagnostics.inputProblem(body: String(repeating: "字", count: 4001), requestID: nil) == .bodyTooLong, "diagnosis identifies oversized shortcut input")
        try expect(SMSReceptionDiagnostics.inputProblem(body: body, requestID: "2026/10/03 14:08") == .invalidRequestID, "diagnosis identifies formatted display dates used as IDs")
        try expect(SMSReceptionDiagnostics.inputProblem(body: body, requestID: " \n ") == nil, "blank shortcut ID can be generated by app")

        let suiteName = "Daylight-sms-diagnostics-tests-\(UUID().uuidString)"
        let defaults = UserDefaults(suiteName: suiteName)!
        defer { defaults.removePersistentDomain(forName: suiteName) }
        var attempt = SMSReceptionDiagnostics.begin(bodyLength: body.utf16.count, at: receivedAt, defaults: defaults)
        try expect(SMSReceptionDiagnostics.latest(defaults: defaults)?.outcome == .started, "intent invocation is visible before store work finishes")
        SMSReceptionDiagnostics.advance(&attempt, to: .save, defaults: defaults)
        SMSReceptionDiagnostics.succeed(&attempt, result: normal.result, at: receivedAt.addingTimeInterval(1), defaults: defaults)
        let saved = SMSReceptionDiagnostics.latest(defaults: defaults)
        try expect(saved?.outcome == .recorded && saved?.stage == .save && saved?.finishedAt == receivedAt.addingTimeInterval(1), "diagnostic success follows completed local save")

        attempt = SMSReceptionDiagnostics.begin(bodyLength: Int.max, at: receivedAt.addingTimeInterval(2), defaults: defaults)
        let untrusted = NSError(domain: "测试商户-尾号9876-20261003140820001", code: 42, userInfo: [NSLocalizedDescriptionKey: body])
        SMSReceptionDiagnostics.fail(&attempt, at: .save, error: untrusted, time: receivedAt.addingTimeInterval(3), defaults: defaults)
        let failed = SMSReceptionDiagnostics.latest(defaults: defaults)
        try expect(failed?.outcome == .failed && failed?.problem == .saveFailed && failed?.errorCategory == .other && failed?.errorCode == 42, "diagnostic keeps safe error category and code")
        try expect(failed?.bodyLength == 4001 && failed?.attemptedAt == receivedAt.addingTimeInterval(2), "only latest attempt is retained with bounded length")
        let encoded = String(data: defaults.data(forKey: SMSReceptionDiagnostics.storageKey)!, encoding: .utf8)!
        try expect(!encoded.contains("测试商户") && !encoded.contains("9876") && !encoded.contains("20261003140820001") && !encoded.contains("34.50") && !encoded.contains("95588"), "diagnostic excludes body sender card merchant user ID and arbitrary error details")
        try expect(SMSReceptionDiagnostics.decode(Data(repeating: 32, count: 4097)) == nil && SMSReceptionDiagnostics.decode(Data("broken".utf8)) == nil, "malformed or oversized diagnostic is ignored")

        var loadAttempt = SMSReceptionDiagnostics.begin(bodyLength: 10, at: receivedAt, defaults: defaults)
        let loadError = NSError(domain: NSCocoaErrorDomain, code: NSFileReadNoPermissionError)
        SMSReceptionDiagnostics.fail(&loadAttempt, at: .load, error: loadError, defaults: defaults)
        try expect(loadAttempt.problem == .recordsUnreadable && loadAttempt.errorCategory == .cocoa && loadAttempt.errorCode == NSFileReadNoPermissionError, "unreadable records are identified separately from input and save failures")
        let appError = AppFailure.message("没有收到短信正文")
        SMSReceptionDiagnostics.fail(&loadAttempt, at: .input, error: appError, problem: .emptyBody, defaults: defaults)
        try expect(loadAttempt.problem == .emptyBody && loadAttempt.errorCategory == .app && loadAttempt.errorCode == 1, "AppFailure diagnosis keeps readable static guidance and bridged error code")
        let exported = String(data: try BackupCodec.export(enabled), encoding: .utf8)!
        try expect(!exported.contains("smsReception") && !exported.contains("errorCategory") && !exported.contains("bodyLength"), "diagnostics stay outside complete-record backups")
        return checks
    }
}
